<?php require_once('../inc/header.php'); ?>

<div class="terms_of_service">
    <div class="terms_of_service_container">
        <h1>eDelivery TERMS & CONDITIONS</h1>
        <p>The Company reserves the right to modify the terms and conditions of this Agreement or its policies relating to the Service or Software at any time, effective upon posting of an updated version of this Agreement on the Service or Software. You are responsible for regularly reviewing this Agreement. Continued use of the Service or Software after any such changes shall constitute your consent to such changes.</p>
        <p>The Company does not provide passenger, logistics or courier services, and the Company is not a logistics carrier or a passenger service provider. It is up to the passenger service provider, third party courier or logistics provider, courier or vehicle operator to offer ride and courier services which may be scheduled through use of the software or service. The company offers information and a method to obtain such passenger or third party courier services, but does not and does not intend to provide the aforementioned services or act in any way as a courier or passenger service provider, and has no responsibility or liability for any passenger, courier services other than the services stated herein provided to you by such third parties. The company does not also provide laundry or food services and shall therefore not bear any responsibility or be liable for loss or damage howsoever caused by or arising in relation thereto.</p>
        <h3>Representations and Warranties</h3>
        <p>By using the Software or Services, you expressly represent and warrant that you are legally entitled to enter this Agreement. The Service and Software are not available to children (persons under the age of 18). By using the Software or Services, you represent and warrant that you are at least 18 years old. By using the Software or the Services, you represent and warrant that you have the right, authority and capacity to enter into this Agreement and to abide by the terms and conditions of this Agreement. Your participation in using the Service and/or Software is for your sole, personal use. You may not authorize others to use your user status, and you may not assign or otherwise transfer your user account to any other person or entity. When using the Software or Service you agree to comply with all applicable laws of the Republic of Kenya. You may only access the Services using authorized means. It is your responsibility to check to ensure you download the correct Software for your device. The Company is not liable if you do not have a compatible handset or if you have downloaded the wrong version of the Software for your handset. The Company reserves the right to terminate this Agreement should you be using the Service or Software with an incompatible or unauthorized device.</p>
        <p>By using the Software or the Services, you agree that:</p>
        
           <ol>
            <li>You will only use the Service or Software for lawful purposes; you will not use the</li>
            <li>Services for sending or storing any unlawful material or for fraudulent purposes. Any packages tendered for delivery shall be subject to random checks for restricted and illegal substances upon reasonable suspicion by the courier service provider. Where the checks reveal any potentially corrosive, poisonous or explosive contents or unlawful material the courier service provider shall decline delivery of the package and immediately notify the Company.</li>
            <li>You will not use the Service or Software to cause nuisance, annoyance or inconvenience.</li>
            <li>You will not impair the proper operation of the network.</li>
            <li>You will not try to harm the Service Providers or Software in any way whatsoever.</li>
            <li>You will not copy, or distribute the Software or other content without written permission from the Company.</li>
            <li>You will only use the Software and Service for your own use and will not resell it to a third party.</li>
            <li>You will keep secure and confidential your account password or any identification we provide you which allows access to the Service.</li>
            <li>You will provide us with whatever proof of identity we may reasonably request.</li>
            </ol>

        <h3>Payment Terms</h3>
        <p>Any fees which the Company may charge you for the Software or Services, are exclusive of all taxes and levies, are due immediately and are non refundable. This no refund policy shall apply at all times regardless of your decision to terminate your usage, our decision to terminate your usage, disruption caused to our Software or Services either planned, accidental or intentional, or any reason whatsoever. The Company reserves the right to determine the final prevailing pricing ‐ Please note the pricing information published on the website may not reflect the prevailing pricing.

The Company, at its sole discretion, may make promotional offers with different features and different rates to any of our customers. These promotional offers, unless made to you, shall have no bearing whatsoever on your offer or contract. The Company may change the fees for our Services or Software as we deem necessary for our business. We encourage you to check back at our website periodically if you are interested about how we charge for the Services or Software.</p>
        <h3>Intellectual Property Ownership</h3>
        <p>The Company alone (and its licensors, where applicable) shall own all right, title and interest, including all related intellectual property rights, in and to the Software and the Services and any suggestions, ideas, enhancement requests, feedback, recommendations or other information provided by you or any other party relating to the Software or the Services. This Agreement is not a sale and does not convey to you any rights of ownership in or related to the Software or the Service, or any intellectual property rights owned by the Company. The Company name, the Company logo, and the product names associated with the Software and Service are trademarks of the Company or third parties, and no right or license is granted to use them</p>
        <h3>Third Party Interactions</h3>
        <p>During use of the Software and Service, you may enter into correspondence with, purchase goods and/or services from, or participate in promotions of third party service providers, advertisers or sponsors showing their goods and/or services through the Software or Service. Any such activity, and any terms, conditions, warranties or representations associated with such activity, is solely between you and the applicable third‐party. The Company and its licensors shall have no liability, obligation or responsibility for any such correspondence, purchase, transaction or promotion between you and any such third‐party. The Company does not endorse any sites on the Internet that are linked through the Service or Software, and in no event shall the Company or its licensors be responsible for any content, products, services or other materials on or available from such sites or third party providers. The Company provides the Software and Service to you pursuant to the terms and conditions of this Agreement. You recognize, however, that certain third‐party providers of goods and/or services may require your agreement to additional or different terms and conditions prior to your use of or access to such goods or services, and the Company disclaims any and all responsibility or liability arising from such agreements between you and the third party providers.</p>
        <p>The Company may rely on third party advertising and marketing supplied through the Software or Service and other mechanisms to subsidize the Software or Service. By agreeing to these terms and conditions you agree to receive such advertising and marketing. If you do not want to receive such advertising you should notify us in writing. The Company reserves the right to charge you a higher fee for the Services or Software should you choose not to receive these advertising services. This higher fee, if applicable, will be posted on the Company's website located at h ttp://sendy.co.ke . The Company may compile and release information regarding you and your use of the Software or Service on an anonymous basis as part of a customer profile or similar report or analysis. You agree that it is your responsibility to take reasonable precautions in all actions and interactions with any third party you interact with through the Service.</p>
    </div>
</div>

<?php require_once('../inc/footer.php'); ?>